[project]
name        = 'rx_selection'
description = 'Project used to apply selection to ntuples used for RX measurements filtered and skimmed by post_ap project'
version     = '0.0.4'
readme      = 'README.md'
dependencies= [
'data-manipulation-utilities',
'rx_data',
'numpy',
'jacobi',
'pandas',
'numpy',
'matplotlib',
'ap_utilities'
]

[project.optional-dependencies]
dev  = ['pytest']

[tools.setuptools.packages.find]
where   = ['src']

[project.scripts]
apply_selection ='rx_selection_scripts.apply_selection:main'

[tool.setuptools.package-data]
'rx_selection_data' = ['*.yaml']

[tool.setuptools]
script-files=[
'src/rx_selection_scripts/submit_selection',
'src/rx_selection_scripts/job_sel_ihep',
]
