[project]
name        = 'rx_selection'
description = 'Project used to apply selection to ntuples used for RX measurements filtered and skimmed by post_ap project'
version     = '0.1.1'
readme      = 'README.md'
dependencies= [
'data-manipulation-utilities',
'rx_data',
'numexpr',
'numpy',
'jacobi',
'joblib',
'pandas',
'numpy',
'matplotlib',
'ap_utilities'
]

[project.optional-dependencies]
dev  = ['pytest']

[tools.setuptools.packages.find]
where   = ['src']


